### ISSUE TITLE
Something wrong with the encoder?

### ISSUE THREAD

**Issue by CaffreyR** [asap-report/lstm-visualisation#31]
Follow your instruction, we got the vector(90,2), which is (maxlen, 2), so each point on the plot is not means a time step but a item in padding? @ptempczyk @sliwy @xu-song 
<img width="829" alt="image" src="https://user-images.githubusercontent.com/84232793/168523616-4b4b283f-0831-43ce-b016-480a5af9eac3.png">
However, in your medium you said 90 is your time step but your lstm is 100.

**Comment by ptempczyk** [comment]
LSTM layer has 100 cells, and padding is made to make each sequence equal in time steps, so each sequence has 90 time steps

**Comment by CaffreyR** [comment]
I misunderstood it sorry! Thanks for your answer!
